// Writes a migration that loads disposable email domains into
// private.blocked_email_domains, which the sign-up hook checks
// (supabase/migrations/*_signup_hook.sql). The list is the community-kept
// disposable-email-domains/disposable-email-domains blocklist. Rerun now and
// then for a fresh list, then `supabase db push`; domains already loaded are
// kept.
//   node scripts/disposable-domains.mts
import { writeFileSync } from 'node:fs'

const SOURCE = 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf'
// Never blocked, whatever the list says: relays real people sign up through
// (Sign in with Apple's "Hide My Email") and the big providers.
const NEVER = new Set([
  'privaterelay.appleid.com',
  'icloud.com',
  'me.com',
  'gmail.com',
  'googlemail.com',
  'outlook.com',
  'hotmail.com',
  'live.com',
  'yahoo.com',
  'proton.me',
  'protonmail.com',
  'pixlfoundation.com'
])

const res = await fetch(SOURCE)
if (!res.ok) throw new Error(`${SOURCE}: HTTP ${res.status}`)
const domains = [
  ...new Set(
    (await res.text())
      .split('\n')
      .map((l) => l.trim().toLowerCase())
      .filter((d) => d && !d.startsWith('#') && /^[a-z0-9.-]+\.[a-z0-9-]+$/.test(d) && !NEVER.has(d))
  )
].sort()
if (domains.length < 1000) throw new Error(`only ${domains.length} domains; is the list still at ${SOURCE}?`)

const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14)
const file = `supabase/migrations/${stamp}_blocked_email_domains.sql`
const rows = domains.map((d) => `  ('${d}')`).join(',\n')
writeFileSync(
  file,
  `-- Generated by scripts/disposable-domains.mts from\n-- ${SOURCE}\n-- ${domains.length} domains. Rerun the script for a fresh list rather than editing this.\n\n` +
    `insert into private.blocked_email_domains (domain) values\n${rows}\non conflict do nothing;\n`
)
console.log(`${file}: ${domains.length} domains`)
